"""add verified to user

Revision ID: 734b4c55fcac
Revises: 382526f9d608
Create Date: 2025-11-22 14:27:29.503725

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '734b4c55fcac'
down_revision = '382526f9d608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True, server_default=sa.false()))

    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=True, server_default=sa.false()))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('student', schema=None) as batch_op:
        batch_op.drop_column('verified')

    with op.batch_alter_table('faculty', schema=None) as batch_op:
        batch_op.drop_column('verified')

    # ### end Alembic commands ###
